# Generated by Django 5.1.8 on 2025-04-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_table_delete_teamchef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
    ]
