# Generated by Django 5.1.8 on 2025-04-11 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_table_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name_plural': 'Table'},
        ),
    ]
