# Generated by Django 5.1.8 on 2025-04-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_table_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
