# Generated by Django 5.1.8 on 2025-04-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_category_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryid',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
