# Generated by Django 5.1.8 on 2025-04-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_category_categoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryid',
        ),
    ]
