# Generated by Django 5.1.8 on 2025-04-17 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_categorya_producta_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producta',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.categorya'),
        ),
    ]
