# Generated by Django 5.1.8 on 2025-04-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_producta_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef_name', models.CharField(max_length=30)),
                ('chef_designation', models.CharField(max_length=30)),
                ('chef_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
